//Login, sign up
export const USER_SIGNIN_API = 'USER_SIGNIN_API';
export const USLOGIN = 'USLOGIN';
export const USER_SIGNUP_API = 'USER_SIGNUP_API';
export const SIGN_UP_NOTIFICATION = 'SIGN_UP_NOTIFICATION';

//Project management
export const GET_ALL_PROJECT_CATEGORY_SAGA = 'GET_ALL_PROJECT_CATEGORY_SAGA';
export const GET_ALL_PROJECT_CATEGORY = 'GET_ALL_PROJECT_CATEGORY';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_LIST_PROJECT = 'GET_LIST_PROJECT';
export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL';
export const GET_PROJECT_DROPDOWN_LIST_SAGA = 'GET_PROJECT_DROPDOWN_LIST_SAGA';
export const GET_PROJECT_DROPDOWN_LIST = 'GET_PROJECT_DROPDOWN_LIST'

//Drawer
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_PROJECT';
export const SET_SUBMIT_EDIT_PROJECT = 'SET_SUBMIT_EDIT_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK';
export const SET_SUBMIT_CREATE_TASK = 'SET_SUBMIT_CREATE_TASK';
export const SET_SUBMIT_EDIT_USER = 'SET_SUBMIT_EDIT_USER';
export const OPEN_FORM_EDIT_USER = 'OPEN_FORM_EDIT_USER';
export const OPEN_FORM_CREATE_USER = 'OPEN_FORM_CREATE_USER';
export const SET_SUBMIT_CREATE_USER = 'SET_SUBMIT_CREATE_USER';

//User management
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const ADD_USER_PROJECT_SAGA = 'ADD_USER_PROJECT_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID';
export const GET_LIST_USER_SAGA = 'GET_LIST_USER_SAGA';
export const GET_LIST_USER = 'GET_LIST_USER';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';
export const UPDATE_USER_SAGA = 'UPDATE_USER_SAGA';
export const EDIT_USER = 'EDIT_USER';
export const CREATE_USER_SAGA = 'CREATE_USER_SAGA';

//Status
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';
export const GET_ALL_STATUS = 'GET_ALL_STATUS';

//Priority
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA';
export const GET_ALL_PRIORITY = 'GET_ALL_PRIORITY';

//Task management
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';
export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL';
export const CHANGE_ASSIGNEES = 'CHANGE_ASSIGNEES';
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN';
export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA';
export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA';
//Comment
export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA';
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const CREATE_COMMENT_SAGA = 'CREATE_COMMENT_SAGA';
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA';
